### ISSUE TITLE
Explain calculation reports

### ISSUE THREAD

**Issue by dvadym** [OpenMined/PipelineDP#10]
## Context

DP computations are pretty different from corresponding non-DP ones. Explains calculation reports will help users to understand how their data is being transformed and which key transformations and parameters that were used. [More details](https://docs.google.com/document/d/12fGPsf678R2AGb9x1xicRhfMTj4IbZK8zddApK667uE/edit?resourcekey=0-Leq3Y6bPlYzDUBfEZcYIgA#bookmark=id.s1468r89lp53). 

## Goals

Implement class **ReportGenerator**.

**Note**: the exact text/format of reports is not that important for now, we will polish it later.

## API

```
class ReportGenerator:
  def __init__(self, name):

  def add_stage(self, text_fn):  # text_fn is a function that return **string**, that’s because sometimes the text is known only when the pipeline is constructed 

  def generate_report(self) -> str:

```

**Comment by jspacek** [comment]
@dvadym I'm interested in working on this issue, if that works!

**Comment by dvadym** [comment]
@jspacek Sure, thank you! 

For now the idea is to have a class ReportGenerator that implements a basic infrastructure - adding messages and generating text reports. I think in future it will be an interesting exercise to make report more informative for PipelineDP users.

**Comment by jspacek** [comment]
@dvadym That sounds great! I've added a WIP #21 to get a start on the basic `ReportGenerator` based on the class in `private_beam` prototype.
