### ISSUE TITLE
Secure noise

### ISSUE THREAD

**Issue by dvadym** [OpenMined/PipelineDP#11]
## Context

The standard random sampling does not provide privacy. More details are in the [paper](https://crysp.uwaterloo.ca/courses/pet/F18/cache/Mironov.pdf).

So a DP aggregation system should have “secure” noise implementation.

## Goals

Make Laplace and Gaussian secure noise available in PipelineDP.

## Possible approaches

1. Implement in Python.
2. Use [PyDP wrapper](https://github.com/OpenMined/PyDP) over C++ library (it’s probably needed to update C++ interface).

**Note**: some investigation/experimentation/discussions are required in order to figure out the best approach.

## Links

1. [Doc](https://github.com/google/differential-privacy/blob/main/common_docs/Secure_Noise_Generation.pdf) on Google C++/Java/Go implementation
2. Google DP library C++ secure noise [implementation](https://github.com/google/differential-privacy/blob/main/cc/algorithms/numerical-mechanisms.h) (both Laplace and Gaussian).
3.  [OpenMined PyDP](https://github.com/OpenMined/PyDP) wrapper for Google DP C++ library

**Comment by jspacek** [comment]
👋  I'm interested in working on this! 

If there are other folks interested, maybe we could start with reviewing some of the reading materials as a group 📖 

Thanks!

**Comment by AbinavRavi** [comment]
Hello I am interested in working on this as well.

**Comment by say-yam** [comment]
Me too, i am also interested in implementing it.

**Comment by dvadym** [comment]
Thanks for the interest! 

There is a good question about implementing secure noise in Python or using C++ wrappers. 

There are a few questions:
1. Whether Python implementation would be fast enough
2. How easy is it to use C++ wrapper in PipelineDP

**Comment by AbinavRavi** [comment]
@say-yam can you please give your openmined slack id??

**Comment by walexi** [comment]
wondering if i can still join u guys on this ?

**Comment by say-yam** [comment]
> @say-yam can you please give your openmined slack id??

Sanyam Chaudhary

**Comment by chinmayshah99** [comment]
@AbinavRavi @walexi @say-yam it would be great if you could use the pipelineDP slack channel for open discussions.

**Comment by dvadym** [comment]
It was implemented
