### ISSUE TITLE
Implement select_partition API function

### ISSUE THREAD

**Issue by dvadym** [OpenMined/PipelineDP#122]
# Context
The goal of this task is to implement an API function for private set computations, namely to output in DP way elements from some set. Those elements are called partitions. The main building blocks for this algorithm have already been implemented for [aggregate()](https://github.com/OpenMined/PipelineDP/blob/1533705126c2e0bbd11165199c4cf51a02994b54/pipeline_dp/dp_engine.py#L43) function.

# API
```
def select_partitions(self, col, params: SelectPartitionParams,
                                 data_extractors: DataExtractors):
```

1. `SelectPartitionParams` contains information that needed for partition selection, which would be subset of [AggregateParams](https://github.com/OpenMined/PipelineDP/blob/1533705126c2e0bbd11165199c4cf51a02994b54/pipeline_dp/aggregate_params.py#L41).
2. `data_extractors` ([DataExtractors](https://github.com/OpenMined/PipelineDP/blob/1533705126c2e0bbd11165199c4cf51a02994b54/pipeline_dp/dp_engine.py#L19)) should have `privacy_id_extractor` and `parition_extractor` (no need in `value_extractor`).
3. The output is a collection with elements `(partition)`

# Notes on implementation
Let’s for now use only truncated geometric method ([code](https://github.com/OpenMined/PipelineDP/blob/1533705126c2e0bbd11165199c4cf51a02994b54/pipeline_dp/dp_engine.py#L181)), which is already used in `aggregate()`

The algorithm for `select_partitions` is the following
1. Do [contribution bounding](https://github.com/OpenMined/PipelineDP/blob/1533705126c2e0bbd11165199c4cf51a02994b54/pipeline_dp/dp_engine.py#L111).
2. Compute number of privacy ids per partition (preferable with using existing aggregations :) ).
3. Do partition selection (preferable with already implemented [_select_private_partitions](https://github.com/OpenMined/PipelineDP/blob/1533705126c2e0bbd11165199c4cf51a02994b54/pipeline_dp/dp_engine.py#L160))

**Comment by sushkoy** [comment]
I'll be looking into that.

**Comment by dvadym** [comment]
sure
