### ISSUE TITLE
Linux Support on pip

### ISSUE THREAD

**Issue by wenhuizhang** [OpenMined/PipelineDP#243]
## Description
pip missing support for pipelineDP on Linux

## How to Reproduce
```
[root@iZbp1flguy1vkvhcyxmq60Z PipelineDP]# pip3 install pipeline-dp
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting pipeline-dp
  Could not find a version that satisfies the requirement pipeline-dp (from versions: )
No matching distribution found for pipeline-dp
```

**Comment by dvadym** [comment]
You have Python 3.6. There are pip packages for Python of versions >=3.7 (according to [wiki page](https://en.wikipedia.org/wiki/History_of_Python) Python 3.6 is no longer officially supported).

You can install a newer version of Python and everything should work.

**Comment by wenhuizhang** [comment]
Still the same error after updating

wenhui.zhang@n231-227-105:~$ python3 --version
Python 3.10.2
wenhui.zhang@n231-227-105:~$  pip3 install pipeline-dp
Defaulting to user installation because normal site-packages is not writeable
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't c
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't c
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't c
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't c
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't c
Could not fetch URL https://pypi.org/simple/pipeline-dp/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(hos
ERROR: Could not find a version that satisfies the requirement pipeline-dp (from versions: none)
ERROR: No matching distribution found for pipeline-dp
