### ISSUE TITLE
Computing DP variance

### ISSUE THREAD

**Issue by dvadym** [OpenMined/PipelineDP#255]
## Context

The [Combiner Framework](https://github.com/OpenMined/PipelineDP/blob/4fa2197eb97044df6b5aed3887b35892da2a4440/pipeline_dp/combiners.py#L25) has been developed for flexible computing DP metrics (based on when the user requested).

The combiner is the object that accumulates values and produces the aggregated result. The computing of all Differential Private (DP) metrics is done in corresponding combiners.

Computing of COUNT, SUM, MEAN, VARIENCE might be achieved in one accumulator using summation, [more details](https://docs.google.com/document/d/12fGPsf678R2AGb9x1xicRhfMTj4IbZK8zddApK667uE/edit?resourcekey=0-Leq3Y6bPlYzDUBfEZcYIgA#bookmark=id.aw7wfzc3ylo9).
 
## Goals

Implement class **VarianceCombiner** which computes any subset of **COUNT**, **SUM**, **MEAN**, **VARIENCE** metrics.

## API

```
class Metrics(Enum):  # it already exists
    COUNT = 'count',
    SUM = 'sum',
    MEAN = 'mean',
    VARIENCE = 'varience'

class VarianceCombiner(Combiner):
     def __init__(self, params: CombinerParams,
                         metrics_to_compute: Iterable[str]):
     def create_accumulator(self, values: Iterable[float]) -> AccumulatorType:
     def merge_accumulators(self, accum1: AccumulatorType
                           accum2: AccumulatorType):
     def compute_metrics(self, accum: AccumulatorType) -> dict:
```

## Notes

1.It's very similar to [MeanCombiner](https://github.com/OpenMined/PipelineDP/blob/4fa2197eb97044df6b5aed3887b35892da2a4440/pipeline_dp/combiners.py#L238)
2.Computation of variance from count, sum, sum of squaares is [implemented](https://github.com/OpenMined/PipelineDP/blob/4fa2197eb97044df6b5aed3887b35892da2a4440/pipeline_dp/dp_computations.py#L378).

**Comment by RamSaw** [comment]
I would like to take this one, could you assign it to me?

**Comment by dvadym** [comment]
Sure, thank you!
