### ISSUE TITLE
Auto-tunning contribution bounding parameters

### ISSUE THREAD

**Issue by dvadym** [OpenMined/PipelineDP#261]
# Context

[DPEngine.aggregate](https://github.com/OpenMined/PipelineDP/blob/41b70a3c7e19b82024e2d0f44842aaab570440bd/pipeline_dp/dp_engine.py#L52) is API function that performs DP aggregation. [Parameters](https://github.com/OpenMined/PipelineDP/blob/41b70a3c7e19b82024e2d0f44842aaab570440bd/pipeline_dp/aggregate_params.py#L55) of this function include parameters related to contribution bounding (`max_partitions_contributed`,  `max_contributions_per_partition`). 

For `max_partitions_contributed`,  `max_contributions_per_partition` if a privacy unit (definition of privacy unit and more on contribution bounding is [here](https://pipelinedp.io/key-definitions/) ) contributes more, contributions are sub-sampled. So smaller these parameters, bigger the ratio of input data which is dropped, but smaller DP noise is added. So there is a trade-off of choosing those parameters. Choosing optimal (in some sense) parameters is data dependent.

# Goals
To introduce estimating "good" `max_partitions_contributed` and `max_contributions_per_partition` with differential privacy, that allow to achieve reasonable accuracy.

**Note:** this is researchy problem, it will require experimenting and knowledge of Differential Privacy. There is no clear best solution and there are many possible approaches.

**Some ideas:**
1. Choosing `max_partitions_contributed` and  `max_contributions_per_partition` might be performed independently (at least probably that's a good start)
2. Choosing `max_partitions_contributed` and  `max_contributions_per_partition` might be considered as a selection problem and for example [exponential mechanism](https://en.wikipedia.org/wiki/Exponential_mechanism_(differential_privacy)) might be used.
3. There might be many different score functions to be used - for example some tradeoff between dropped data and DP noise or that dropped data because of sampling are around some fixed ratio (say 1%).

I'm ready to help in discussions and experimenting.

**Comment by RamSaw** [comment]
I would like to work on this.

**Comment by dvadym** [comment]
Thank you!
