### ISSUE TITLE
Support max_contribution_per_user contribution bounding

### ISSUE THREAD

**Issue by dvadym** [OpenMined/PipelineDP#263]
# Context

## Definitions
_Contribution bounding_ is a process of limiting contributions by a single individual (or an entity represented by a privacy key) to the output dataset or its partition. This is key for DP algorithms, since protecting unbounded contributions would require adding infinite noise.

_Cross-partition contribution bounding_ is a procedure which ensures that each individual contributes to a limited number of partitions.

_Per-partition contribution bounding_ is a procedure which ensures that each individual’s contribution to any single partition is bounded.

More details on the terminology is [here](https://pipelinedp.io/key-definitions/).

## How contribution bounding is performed
[DPEngine.aggregate](https://github.com/OpenMined/PipelineDP/blob/41b70a3c7e19b82024e2d0f44842aaab570440bd/pipeline_dp/dp_engine.py#L52) performs DP aggregations (sum, count, mean etc). In order to apply [Laplace/Gaussain mechanisms](https://en.wikipedia.org/wiki/Additive_noise_mechanisms) queries need to have a bounded sensitivity. For this purposes contribution bounding of each individual is required. 

Now contribution bounding is controlled with `max_partitions_contributed` (cross partition) and `max_contributions_per_partition` (per partition) fields of  [AggregateParams](https://github.com/OpenMined/PipelineDP/blob/41b70a3c7e19b82024e2d0f44842aaab570440bd/pipeline_dp/aggregate_params.py#L55).

[Code](https://github.com/OpenMined/PipelineDP/blob/41b70a3c7e19b82024e2d0f44842aaab570440bd/pipeline_dp/dp_engine.py#L253) that performs contribution bounding.

## Computing sensitivities.
For the Laplace mechanism [L1](https://en.wikipedia.org/wiki/Lp_space) sensitivity is required, for the Gaussian mechanism L2 sensitivity is required. `max_contributions` is L1 sensitivity. For integer valued vector `|x|`, it's known that 

`|x|_2 <= |x|_1` (i.e. L2-norm <= L1-norm). 

i.e. we can estimate L2 sensitivity with L1 sensitivity

# Goals
Implement support of **max_contributions** contribution bounding, which consists

1. To introduce parameter `max_contributions` in [AggregateParams](https://github.com/OpenMined/PipelineDP/blob/41b70a3c7e19b82024e2d0f44842aaab570440bd/pipeline_dp/aggregate_params.py#L55).
2. Implement code which ensures that no more than `max_contributions` rows per privacy_id are preserved (probably [_bound_contributions()](https://github.com/OpenMined/PipelineDP/blob/41b70a3c7e19b82024e2d0f44842aaab570440bd/pipeline_dp/dp_engine.py#L253) is a good starting point).
3. Implement computations of sensitivies, namely we need to update finding sensitivities in [_add_random_noise](https://github.com/OpenMined/PipelineDP/blob/bb4046265e155f45cdd7b4ee91b8d595c1089c72/pipeline_dp/dp_computations.py#L150) based on section computing sensitivities

**Comment by dvadym** [comment]
Thank you!

**Comment by manavgarg** [comment]
Do you want to create another issue for tracking the remaining work on computing sensitivities?

**Comment by dvadym** [comment]
### Implementation of computations of sensitivies in based on `max_contributions`

Note: this is a missing part of finishing this task.

#### DP theory
We need sensitivities for [Laplace](https://en.wikipedia.org/wiki/Additive_noise_mechanisms#Laplace_Mechanism) (L1-sensitivity) and [Gaussian](https://en.wikipedia.org/wiki/Additive_noise_mechanisms#Gaussian_Mechanism) mechanism (L2-sensitivity).

[AggregateParams](https://github.com/OpenMined/PipelineDP/blob/66012f04a94720ba2e5499c1c96edb3399b83287/pipeline_dp/aggregate_params.py#L57) has contribution bounding parameters, which translated to L1, L2 sensitivities
```
    max_partitions_contributed: Optional[int] = None
    max_contributions_per_partition: Optional[int] = None
    max_contributions: Optional[int] = None
    min_value: float = None
    max_value: float = None
```
Consider how it's translated to computing sum. The output of sum query is 
`(s_1, ... , s_n)`, where s_i is the sum per i-th partition (any ordering of partition can be chosen).

Then sensitity is how much 1 privacy id can influence the sum query. Let we have some privacy id  `p_id1`, without loss of generality we can assume that all s_i = 0, w/o dataset **D** w/o `p_id1`, the question what is the maximum norm (L1, L2), for **D** union `p_id1`.

Let `max_abs_value = max(|min_value|, |max_value|)`.

**L1 senstivity:**   

`max_partitions_contributed*max_contributions_per_partition*max_abs_value`

or

`max_contributions*max_abs_value`.

**L2 sensitivity**
`sqrt(max_partitions_contributed)*max_contributions_per_partition*max_abs_value`

or 

`max_contributions*max_abs_value` (which is equal L1-sensitivity)

#### Code changes
In this PR `max_contributions` was introduced, so some changes in computations are required. All changes will be in `dp_computations.py`. 

Namely, we need to propagate l1_sensitivity based on `max_contributions` to [_add_random_noise](https://github.com/OpenMined/PipelineDP/blob/66012f04a94720ba2e5499c1c96edb3399b83287/pipeline_dp/dp_computations.py#L128).

The input to computations is [MeanVarParams](https://github.com/OpenMined/PipelineDP/blob/66012f04a94720ba2e5499c1c96edb3399b83287/pipeline_dp/dp_computations.py#L25) dataclass (we should extend it with `max_contributions`).

So the goal is to propagate `max_contributions` to `_add_random_noise`.

**Comment by manavgarg** [comment]
Thanks for the info. Any additional references to learn more about the theory? I believe it would be interesting for me to dive deeper here.

**Comment by dvadym** [comment]
1. [Data computations in data pipelines reference doc](https://github.com/google/differential-privacy/blob/main/common_docs/Differential_Privacy_Computations_In_Data_Pipelines.pdf) - it's cross-language design doc, which describes how PipelineDP built (section _Noise addtion mechanisms_ contains about computing sensitivites)
2. [Differentially Private SQL with Bounded User Contribution](https://arxiv.org/abs/1909.01917) this is original paper about the system like PipelineDP

**Comment by manavgarg** [comment]
I have been reading https://desfontain.es/privacy/gaussian-noise.html to better understand the mathematical concepts.
I have a few questions/clarifications:
- I understand L1  & L2 sensitivity. But in the code, we have l0 & linf sensitivities. What are the defintions for those?
- In the above case, would this mean that l0 sensitivity is just 1 and linf would be dictated by max_contributions?

**Comment by dvadym** [comment]
For the definition of L0, Linf sensitivities, please look at [Data computations in data pipelines reference doc](https://github.com/google/differential-privacy/blob/main/common_docs/Differential_Privacy_Computations_In_Data_Pipelines.pdf) in section _Noise addtion mechanisms_ page 6.

For `max_contributions` we don't need to worry about l0 and linf. Let's consider `count` sensitivity. 
Then l1 sensitivity = `max_contributions` and l2 sensitivity == l1 sensitivity (that's because l2 norm of integer vectors <= l1 norm)

**Comment by dvadym** [comment]
The missing part of adding the noise based on `max_contributions` was implemented on [PR](https://github.com/OpenMined/PipelineDP/pull/451)
