### ISSUE TITLE
Introduce per partition contribution bounding for sum

### ISSUE THREAD

**Issue by dvadym** [OpenMined/PipelineDP#275]
# Context
**Note:** Terminology might be found [here](https://pipelinedp.io/key-definitions/).

In order to protect data of each user, it's required to make contribution bounding of each user data. There are 2 types of contribution bounding

_Cross-partition contribution bounding_ is a procedure which ensures that each individual contributes to a limited number of partitions.

_Per-partition contribution bounding_ is a procedure which ensures that each individual’s contribution to any single partition is bounded.

In this task let's consider only _per-partition contribution bounding_ for **sum** aggregation. There are 2 options, consider an example how it works. Let privacy_id contributes [1,2,3,4,5] per partition.

1. _Bounding each contribution_ (this currently implemented): let `min_value` = 1, `max_value` = 3, `max_contributions_per_partition` = 3 (those values are set in [AggregateParams](https://github.com/OpenMined/PipelineDP/blob/3a7b87a5d943ea6b083c45934c8bb1110cbe5766/pipeline_dp/aggregate_params.py#L80)).
  
Then the bounding algorithm is the following:
      - randomly sample 3 elements, let the result [1,3, 5]
      - clip values to [1, 3]:  [1,3, 3]
      - sum:  1 + 3 + 3 = 7
      - anonymize with DP: 7 + random noise
  
2. _Bounding aggregated contributions_ (to implement): let `min_sum_per_partition` = 0, `max_sum_per_partition` = 10 (those should be added to `AggregateParams`)
Then the bounding algorithm is the following:
      - sum: 15 = 1+2+3+4+5
      - clip sum to [0, 10]: 10
      - anonymize with DP: 10 + random noise

# Goal
To implement  _bounding aggregated contributions_ for **sum**.

This task might be split on the following parts:
1. Add `min_contributions_per_partition` and `max_contributions_per_partition` to `AggregateParams`.
2. Implement _bounding aggregated contributions_ in [SumCombiner](https://github.com/OpenMined/PipelineDP/blob/3a7b87a5d943ea6b083c45934c8bb1110cbe5766/pipeline_dp/combiners.py#L209)  (`SumCombiner` performs computation of DP sum )
3. Implement `group_by_key` for this type of contribution bounding instead of sampling `sample_fixed_per_key` [here](https://github.com/OpenMined/PipelineDP/blob/3a7b87a5d943ea6b083c45934c8bb1110cbe5766/pipeline_dp/dp_engine.py#L292).

**Note**: there is draft [PR](https://github.com/OpenMined/PipelineDP/pull/213) (3 files in pipeline_dp/*) of this feature which implements 1 and 2, but w/o testing, it might be a good starting point.

**Comment by sunchengxuanivy** [comment]
I'm Ivy and I'm currently working on this issue.

**Comment by dvadym** [comment]
Thank you!

**Comment by dvadym** [comment]
This was implemented on [PR](https://github.com/OpenMined/PipelineDP/pull/308)
