### ISSUE TITLE
Laplace/Gaussian partition selection strategies.

### ISSUE THREAD

**Issue by dvadym** [OpenMined/PipelineDP#281]
# Context

From [key definitions](https://pipelinedp.io/key-definitions/) (see there for more details):

_A partition_ is a subset of the data corresponding to a given value of the aggregation criterion. Usually we want to aggregate each partition separately. For example, if we count visits to restaurants, the visits for one particular restaurant are a single partition, and the count of visits to that restaurant would be the aggregate for that partition.

_A partition key_ is the aggregation key corresponding to a partition.

_Partition selection_ is a process of identifying the partition keys that are safe to release in the sense that they don’t break the DP guarantees and don’t leak any user information.

_Private partition selection_ is _partition selection_ when partition keys are identified from data.

There are multiple strategies how to do _private partition selections_. 3 of them are implemented in [the Google C++ DP building block library](https://github.com/google/differential-privacy/blob/main/cc/algorithms/partition-selection.h) and exposed to Python in [PyDP](https://github.com/OpenMined/PyDP/blob/d48cf6e729f2b659a57ec23a9431e535f6ebd87e/src/pydp/algorithms/partition_selection.py#L28). Those methods are
  1.Truncated geometric.
  2.Laplace thresholding (which works as `if n_privacy_ids + laplace noise > threshould then release`).
  3.Gaussian thresholding (which works as `if n_privacy_ids + laplace noise > threshould then release`).

Now in PipelineDP only the first one is used ([code](https://github.com/OpenMined/PipelineDP/blob/14b4c49d730c58b4e38376dc561c38f1ba8145e8/pipeline_dp/dp_engine.py#L382)).

Different partition selection strategies have own strength and weeknesses, so it makes sense to be able to use all of them.

**In-Depth reading:**
1.[Truncated geometric partition selection](https://arxiv.org/pdf/2006.03684.pdf).
2.[Laplace/Gaussian thresholding](https://github.com/google/differential-privacy/blob/main/common_docs/Delta_For_Thresholding.pdf).

# Goals
Implement possibility to use Laplace/Gaussian thresholding.

Code references:
1. [DPEngine.aggregate](https://github.com/OpenMined/PipelineDP/blob/41b70a3c7e19b82024e2d0f44842aaab570440bd/pipeline_dp/dp_engine.py#L52) is API function that performs DP aggregation, it has an argument `AggregateParams` with all parameters. We need to add field `partition_selection_strategy` with options.
2. [Applying partition selection strategy](https://github.com/OpenMined/PipelineDP/blob/14b4c49d730c58b4e38376dc561c38f1ba8145e8/pipeline_dp/dp_engine.py#L382).

**Comment by tohaowu** [comment]
I will add laplace_partition_strategy and gaussian_partition_strategy in the DPEngine.aggregate.

**Comment by dvadym** [comment]
Thank you!

**Comment by ricardocarvalhods** [comment]
Hi, @tohaowu , are you still working on this?
If not, I'd like to work on it, if you don't mind.

**Comment by tohaowu** [comment]
No, I'm not. Yes, you can. Thanks

**Comment by ricardocarvalhods** [comment]
So this issue can be closed too, right @tohaowu ?

**Comment by tohaowu** [comment]
Yes
