### ISSUE TITLE
Move parameter validation testing to proper place 

### ISSUE THREAD

**Issue by dvadym** [OpenMined/PipelineDP#292]
# Context

[DPEngine.aggregate](https://github.com/OpenMined/PipelineDP/blob/66012f04a94720ba2e5499c1c96edb3399b83287/pipeline_dp/dp_engine.py#L53) is an API function that performs DP aggregations. It takes [AggregateParams](https://github.com/OpenMined/PipelineDP/blob/66012f04a94720ba2e5499c1c96edb3399b83287/pipeline_dp/aggregate_params.py#L57) as an argument. `AggregateParams` is dataclass and specifies details of the computation which is performed. It has pretty complicated validation logic in [\_\_post_init\_\_](https://github.com/OpenMined/PipelineDP/blob/66012f04a94720ba2e5499c1c96edb3399b83287/pipeline_dp/aggregate_params.py#L104). 
Now tests for the validation are via `DPEngine.aggregate` tests ([code](https://github.com/OpenMined/PipelineDP/blob/66012f04a94720ba2e5499c1c96edb3399b83287/tests/dp_engine_test.py#L200)). 

It is better to introduce a separate test.

# Goal
Introduce `aggregate_params_test.py` and move all validation tests to this file.

Bonus task: to add more tests

**Comment by ricardocarvalhods** [comment]
I'll take this one.
