### ISSUE TITLE
Broken examples/restaraunt_visits/run_without_frameworks.py due to deprecated API

### ISSUE THREAD

**Issue by parikhanupk** [OpenMined/PipelineDP#294]
## Description
Running the file examples/restaraunt_visits/run_without_frameworks.py raises an exception due to API change - deprecated AggregateParams.public_partitions.

## How to Reproduce
1. cd examples/restaraunt_visits
2. python run_without_frameworks.py --output_file=output.txt
3. Raises exception - "ValueError: AggregateParams.public_partitions is deprecated. Please use public_partitions argument in DPEngine.aggregate instead."

## Expected Behavior
The script should run without errors and generate the output file.

**Comment by dvadym** [comment]
Thank you @parikhanupk for reporting this issue! I've fixed it.
