### ISSUE TITLE
Detailing the local example to match its jupyter sibling

### ISSUE THREAD

**Issue by parikhanupk** [OpenMined/PipelineDP#297]
## Where?
Where are you looking to add documentation? Which file? Which feature?
https://github.com/OpenMined/PipelineDP/blob/main/examples/restaraunt_visits/run_without_frameworks.py

## Who?
Who is your audience for this documentation issue?
Newcomers wanting to run the example locally.

## What?
Describe what you would like this documentation to accomplish.
Add details to the local example file to match its jupyter sibling (https://github.com/OpenMined/PipelineDP/blob/main/examples/restaurant_visits.ipynb) allowing newcomers to read/run either example with similar content - but strictly for a local example dataset.

**Comment by parikhanupk** [comment]
I ([github.com/](https://github.com/parikhanupk/) will be working on this issue.

**Comment by dvadym** [comment]
Thanks @parikhanupk! Go ahead!
