### ISSUE TITLE
Contribution bounding 

### ISSUE THREAD

**Issue by dvadym** [OpenMined/PipelineDP#3]
## Context

 DP protects contributions of each user. In order to achieve that, it’s necessary to bound user contributions in DP aggregations. 

There are 2 types of the contribution bounding: **cross-partition** and **per-partition** (more details in [the reference doc](https://docs.google.com/document/d/1cvfAU4XwglRgLc7XP9qCf5a6iZRajqVVsH7s5URY-UU/edit#bookmark=id.wnab9om9at6a)).

There are 2 types of per partition bounding: **bounding of each contribution** and **bounding of aggregated contribution** ([more details]( https://docs.google.com/document/d/1cvfAU4XwglRgLc7XP9qCf5a6iZRajqVVsH7s5URY-UU/edit#bookmark=id.fbmdyi21xc9u)). 

## Goals 

1.  Implement per partition-contribution bounding with a method **[bounding of each contribution](https://docs.google.com/document/d/1cvfAU4XwglRgLc7XP9qCf5a6iZRajqVVsH7s5URY-UU/edit#bookmark=id.n6r7jiaksnm7)**  (this method is more general).
2.  Implement cross-partition contribution bounding.

## API 

A method of DPEngine class

     def _bound_cross_partition_contributions(self, col, max_partitions_contributed: int, max_contributions_per_partition: int, aggregator_fn)

  where

  **col** is a collection, with types of each element: (**privacy_id**, **partition_key**, **value**)
 **aggregator_fn** is a function that takes a list of values and returns an **aggregator** object which handles all aggregation logic.

 **output**:((**privacy_id**, **parition_key**), **aggregator**)

**Note**: by performance reasons, it’s convenient to aggregate values during contribution bounding.

## Examples of contribution bounding in the prototype: 
 1. [Per partition contribution](https://github.com/OpenMined/PipelineDP/blob/04a04d2f31e2299135a4000d2134d71d8f121f7b/prototype/private_beam.py#L467) 
 2. [Cross partition contribution ](https://github.com/OpenMined/PipelineDP/blob/04a04d2f31e2299135a4000d2134d71d8f121f7b/prototype/private_beam.py#L476)

**Note:** Please consider the prototype with a grain of salt, it is not a production code.

**Comment by preethiraghavan1** [comment]
I would like to work on this. Please assign to me.

**Comment by dvadym** [comment]
Sure, go ahead! If you have any questions please ask

**Comment by preethiraghavan1** [comment]
#32 is merged. Closing this issue.
