### ISSUE TITLE
Implement DP computing of count, sum, mean, var

### ISSUE THREAD

**Issue by dvadym** [OpenMined/PipelineDP#36]
## Goals

Implement 

```
@dataclass
class MeanVarParams:
    eps: float
    delta: float
    low: float
    high: float
    sensitivity: float              # L1 for Laplace, L2 for Gaussian
    noise_kind: NoiseKind   # Laplace or Gaussian

def compute_dp_count(count, dp_parameters) -> dp_count

def compute_dp_sum(sum, dp_parameters) -> dp_sum

def compute_dp_mean(count, sum, dp_parameters) -> (dp_count, dp_sum, dp_mean)

def compute_dp_var(count, sum, sum_squares, dp_parameters) -> (dp_count, dp_sum, dp_mean, dp_var)

```

### DP algorithm
The main way of anonymizing is adding Laplace or Gaussian noise to non-anonymized values. So computing of dp mean might be

1. Add the random noise to count and sum -> dp_count, dp_sum
2. Compute dp_mean = dp_sum/dp_count

[More details](https://docs.google.com/document/d/1cvfAU4XwglRgLc7XP9qCf5a6iZRajqVVsH7s5URY-UU/edit#bookmark=id.9qngddwqrcef) are in the reference doc.

Note: that there are some additional ways to make utility better, so the final algorithm will be slightly different.

### Secure noise implementation
The standard random sampling does not provide privacy. More details are in the [paper](https://crysp.uwaterloo.ca/courses/pet/F18/cache/Mironov.pdf).

 There is a separate [issue](https://github.com/OpenMined/PipelineDP/issues/11) to make available [PyDP wrappers](https://github.com/OpenMined/PyDP) of secure noise from [Google C++ DP library](https://github.com/google/differential-privacy/tree/main/cc/algorithms). For this issue for the development we can use numpy noise np.random.laplace and np.random.normal. We willreplace with the secure as soon as it is ready.

### Formulas for noise parameters
They might be taken from a [book](https://www.cis.upenn.edu/~aaroth/Papers/privacybook.pdf) 

1. Laplace: Def 3.3, page 32
2. Gaussian: Theorem 3.22, page 53 (it’s not an optimal formula, but it’s simple, let’s use it for now).

**Comment by AlexandraImbrisca** [comment]
I would like to work on this issue if that's okay 👋🏻

**Comment by dvadym** [comment]
Sure, thanks! 

In case of any questions, please let me know.

**Comment by dvadym** [comment]
FYI: I've added 
 compute_dp_count and compute_dp_sum function in the issue description.

I'd suggest to start with compute_dp_count as it is the simplest one and to send PR to review as soon as the 1st implementation is ready, in order to get the earlier feedback. Not necessary for the 1st review iteration to have all tests.

**Comment by AlexandraImbrisca** [comment]
Hi @dvadym,

About computing the mean and the variance, I am thinking whether we can apply the same logic as for count and sum. The only sensitivity changed is linf. For instance, if we compute the mean, the contribution of adding a new user is maximum when the database is small (only one previous user). In this case, the maximum contribution could be (high - low) / 2.

What do you think?

**Comment by dvadym** [comment]
Yeah, that's a great observation! :thumbsup:

We can do mean computation by computing **count** and **sum** of `x_i-(high + low) / 2` - i.e. sum of normalized values.
