### ISSUE TITLE
Implement Accumulator Framework for aggregation

### ISSUE THREAD

**Issue by dvadym** [OpenMined/PipelineDP#37]
# Context
Computing of DP metrics will include pipeline aggregations. For this we need to have some ways to compute those aggregations. This issue is about implementing of basic structure of object that are responsible for aggregations. Let's call such object accumulators.

**Note:** The ideas of accumulators and their API are influence of Apache Beam accumulators (see example 5 on [page](https://beam.apache.org/documentation/transforms/python/aggregation/combineperkey/)).

**Note:** There is an [issue](https://github.com/OpenMined/PipelineDP/issues/9) on implementing **SumAccumulator**. This issue is on introducing the accumulator framework. Which is important since we will have multiple types of accumulators and there might be multiple accumulators per 1 aggregation.

# Goals
To implement

1. Abstract base class

```
class Accumulator(ABC):
     @abstractmethod
     def add_value(v)
     @abstractmethod
     def add_accumulator(self, accumulator:Accumulator) -> Accumulator # returns itself
     @abstractmethod
    def compute_metrics()
```

2. CompoundAccumulator

```
  class CompoundAccumulator(Accumulator):
      def __init__(self, accumulators)
      def merge(cls,  accumulators: Iterable[CompoundAccumulator]) -> CompoundAccumulator 
      def add_value(v)
      def add_accumulator(self, accumulator:CompoundAccumulator) -> CompoundAccumulator # returns itself
      def compute_metrics()
```

  which keeps multiple accumulators (of different types) and delegates **merge()** and **compute_metrics()** to those accumulators.

3. Serialization of accumulator classes.
4. `AccumulatorFactory` is the factory for creating accumulator of specific types with specific parameters (details in next subsection)

## AccumulatorFactory
**API**:
```
class AccumulatorFactory:
   def __init__(params: [AggregateParams])
   def initialize()
   def create(values:List) -> Accumulator
```

[AggregateParams](https://github.com/OpenMined/PipelineDP/blob/5f8e2b5e1265af6e29f3c2fb79d0c9846a63ba43/pipeline_dp/aggregate_params.py#L22) in sources
**Notes** 
1. `AccumulatorFactory` is responsible for creating a right set of accumulators based on `params`.
2. `AccumulatorFactory` will be created during the pipeline construction. `create()` method will be called during the pipeline execution.
3. There will be some additional parts of API (described later).
4. `create()` returns `CompoundAggregator` in case of [params.metrics](https://github.com/OpenMined/PipelineDP/blob/5f8e2b5e1265af6e29f3c2fb79d0c9846a63ba43/pipeline_dp/aggregate_params.py#L38) specifies metrics which requires multiple accumulators (though some accumulators might compute several metrics).

**Implementation details**

1. `AccumulatorParams`:
```
@dataclass
class AccumulatorParams:
    accumulator_type:Type 
    # additional params (this comment is just for context, params will be add later)
```
2.Function for mapping `AggregationParams` to `List[AccumulatorParams]`:
```
def create_accumulator_params(aggregation_params:AggregationParams) -> List[AccumulatorParams]:
   raise NotImplemented()  # implementation will be done later
```
**Note:** Let's mock this function for testing. In Python it's possible to [mock functions](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.patch).

3. `AccumulatorFactory.__init__`  save aggregate_params to a member variable.
4. `AccumulatorFactory.initialize()` creates AccumulatorParams by calling `create_accumulator_params` (and in later PRs it will request privacy budget from [BudgetAccountant](https://github.com/OpenMined/PipelineDP/blob/5f8e2b5e1265af6e29f3c2fb79d0c9846a63ba43/pipeline_dp/budget_accounting.py#L72)). 
The reason why a separate `initialize` is required, and that `__init__` is not enough it is that `initialize()` is called only on initial creation, `__init__` might be called on the workers.
5. `AccumulatorFactory.create()` creates `CompoundAccumulator` (if there are more than 1 `AccumulatorParams`) or specific Accumulator (if there is 1 `AccumulatorParams`), by using `accumulator_type` and passing to values to `accumulator_type` constructor

**Comment by preethiraghavan1** [comment]
Hi Vadym, I would like to work on this. Could you assign this to me?

**Comment by dvadym** [comment]
Sure, thanks!

**Comment by boyaryn** [comment]
What do you think of adding something like `createAccumulator` method or `zeroAccumulator` value to the `Accumulator` class so that we can abstract away accumulator logic while calling `PipelineOperations`' methods (i.e. not to have an additional step to create a collection of (key, accumulator) pairs for input to `SparkRDDOperations.reduce_accumulators_per_key`). This would probably achieve better performance of reducing accumulators in `SparkRDDOperations` because [the current suggested implementation has an overhead of list creation](https://github.com/OpenMined/PipelineDP/pull/46/commits/e6a54e9050b8fedd2be56bc1adf36311c8798a2a#).

**Comment by preethiraghavan1** [comment]
Hi Ivan,

Thanks for your message. I am currently on vacation. I just wanted to acknowledge I did get this message. I will look into it and respond to you as soon as I can. 

Thanks
Preethi

**Comment by dvadym** [comment]
Yeah, I agree that API with merging 1 aggregator makes sense. A suggestion with accumulator list was Beam inspired :).

I've updated the issue description with another argument `accumulator`. I also thought to have one argument of `merge()` that might be one accumulator or list (but type description would be more complicated, and how to name it, in singular or plural).

Do you have any suggestions?

**Comment by boyaryn** [comment]
Hi guys.

Preethi, thanks for letting us know. Enjoy your vacation! :)

Vadim, Beam seems to be a nice framework :) I wish it supported my CPU architecture…

What about the following Accumulator definition?
```
class Accumulator(ABC):
    zeroAccumulator: Accumulator
    def add(v) -> Accumulator
    def merge(accumulator: Accumulator) -> Accumulator
```
(I omitted python decorators.)
This way all Accumulator-specific logic could be contained within Accumulator implementation. Each `reduce_accumulators_per_key` implementation could rely on and delegate to Accumulator's methods.

**Comment by dvadym** [comment]
Thanks for this suggestion!

Yeah, I looked again on 2 arguments - `accumulator` and `accumulators` and didn't like that :). I like suggestion with add.

I've updated the description to

```
     def add_value(v)
     def add_accumulator(self, accumulator:Accumulator) -> Accumulator # returns itself
```

i.e. to have 2 methods, of course there is an option to have one method and `add()` and to check types (accumulator or not inside) but it's better to be more explicit

WDYT?

**Comment by preethiraghavan1** [comment]
Hi Vadym, could you explain more about the CompoundAccumulator? In specific, what would add_value and compute_metrics do? Give out an iterator?

**Comment by dvadym** [comment]
> Hi Vadym, could you explain more about the CompoundAccumulator? In specific, what would add_value and compute_metrics do? Give out an iterator?

The idea that CompoundAccumulator manages case when the API user wants to compute multiple metrics, for example mean and percentile, and there are 2 accumulator classes MeanAccumulator and PercentileAccumulator. Then it might work like this.

acc1 = MeanAccumulator()
acc2 = PercentileAccumulator()

compound_accumulator = CompoundAccumulator(acc1, acc2)  #

**Comment by dvadym** [comment]
> What do you think of adding something like `createAccumulator` method or `zeroAccumulator` value to the `Accumulator` class so that we can abstract away accumulator logic while calling `PipelineOperations`' methods (i.e. not to have an additional step to create a collection of (key, accumulator) pairs for input to `SparkRDDOperations.reduce_accumulators_per_key`). This would probably achieve better performance of reducing accumulators in `SparkRDDOperations` because [the current suggested implementation has an overhead of list creation](https://github.com/OpenMined/PipelineDP/pull/46/commits/e6a54e9050b8fedd2be56bc1adf36311c8798a2a#).

sry, I missed about `zeroAccumulator`. I'm not sure that RDD implementation needs that. Let's discuss on RDD bug.

**Comment by preethiraghavan1** [comment]
> > Hi Vadym, could you explain more about the CompoundAccumulator? In specific, what would add_value and compute_metrics do? Give out an iterator?
> 
> The idea that `CompoundAccumulator` manages a case when the API user wants to compute multiple metrics, for example **mean** and **percentile**, and there are 2 accumulator classes `MeanAccumulator` and `PercentileAccumulator`. Then it might work like this.
> 
> ```
> acc1 = MeanAccumulator()
> acc2 = PercentileAccumulator()
> 
> compound_accumulator = CompoundAccumulator(acc1, acc2)  # compound_accumulator keeps acc1 and acc2
> 
> compound_accumulator.add_value(v) # calls  acc1.add_value(v) and acc1.add_value(v)
> compound_accumulator.add_accumulator(acc) # assumes that acc has the accumulators of the same types and merges them
> compound_accumulator.compute_metrics() # returns [acc1.compute_metrics, acc2.compute_metrics()]
> ```
> 
> Does it make sense?

Yes! Thanks!

**Comment by boyaryn** [comment]
> Thanks for this suggestion!
> 
> Yeah, I looked again on 2 arguments - `accumulator` and `accumulators` and didn't like that :). I like suggestion with add.
> 
> I've updated the description to
> 
> ```
>      def add_value(v)
>      def add_accumulator(self, accumulator:Accumulator) -> Accumulator # returns itself
> ```
> 
> i.e. to have 2 methods, of course there is an option to have one method and `add()` and to check types (accumulator or not inside) but it's better to be more explicit
> 
> WDYT?

DIscussing it [here](https://github.com/OpenMined/PipelineDP/issues/41). :)

**Comment by dvadym** [comment]
FYI: I've updated the issue description with "3. AccumulatorFactory...". 

I'll add more description about `AccumulatorFactory` soon

**Comment by dvadym** [comment]
FYI: I've updated the issue description about `AccumulatorFactory`, which will be a way to create accumulators for running in pipelines.

**Comment by dvadym** [comment]
## Integrating accumulator framework into the pipeline computations

[_bound_contributions](https://github.com/OpenMined/PipelineDP/blob/84bbf45740dcdc197c2c20a75b8eaaf6b1f2ecab/pipeline_dp/dp_engine.py#L71) function has an argument `aggregator_fn`, which takes values and returns accumulator object. `aggregator_fn` might be implemented for example as lambda which calls `AccumulatorFactory.create`.

So integration might be done in the following way:
 In [DPEngine.aggregate()](https://github.com/OpenMined/PipelineDP/blob/84bbf45740dcdc197c2c20a75b8eaaf6b1f2ecab/pipeline_dp/dp_engine.py#L53): 
 1. create `AccumulatorFactory` from `AggregateParams` and create `aggregator_fn`
 2. map collection `col` to collection with elements (privacy_id, partition_key, value) by using `data_extractors`
 3. call `_bound_contributions`

**Comment by dvadym** [comment]
## Implementation of `create_accumulator_params` function
There is already `CountAccumulator` (not fully implemented, but enough for testing), so it's possible to create 1st implementation of `create_accumulator_params`. Moreover having a simple implementation of this function would be a good starting point for extending it, during adding new accumulators.

The idea is that `create_accumulator_params` maps `AggregateParams` to `List[AccumulatorParams]` and `AccumulatorParams` is used for creating accumulators. In future (~6 months) there will be 10+ accumulators, and there might complicated mapping between `AggregateParams` and `AccumulatorParams`, but for now let's start simple:

If [AggregateParams.metrics](https://github.com/OpenMined/PipelineDP/blob/84bbf45740dcdc197c2c20a75b8eaaf6b1f2ecab/pipeline_dp/aggregate_params.py#L38) contains `COUNT` to create AccumulatorParams for [CountAccumulator](https://github.com/OpenMined/PipelineDP/blob/84bbf45740dcdc197c2c20a75b8eaaf6b1f2ecab/pipeline_dp/accumulator.py#L159).
