### ISSUE TITLE
Public partition selection

### ISSUE THREAD

**Issue by dvadym** [OpenMined/PipelineDP#4]
## Context 

**Definition:** The partition keys for a DP algorithm are **public** if they are known in advance. 

**The public partition selection** is a procedure that ensures that the output contains all public partitions and only them. [More details](https://docs.google.com/document/d/1cvfAU4XwglRgLc7XP9qCf5a6iZRajqVVsH7s5URY-UU/edit#bookmark=id.mp21ow1ze2ps).

There are 2 types of public partition selection - **with join operation** and **in-memory**.

## Goals

1. Implement removing non-public partitions with a **join**.
2. Implement adding public partitions which are missing in the input.
3. Implement removing non-public partitions with a **in-memory** public partitions.

**Note:** The 2nd part is blocked on other tasks.

**Note:** All of those parts are independent. The 3rd part is an optimization of 1st, but it's less general, so 1st has a higher priority.

## API for goals 1 and 3

A method of DPEngine class

  `def _drop_not_public_partitions(self, col, public_partitions)`

**col** is a collection (multimap) of (**partition_key**, **data**) (type of data is not important)
**public_partitions** is a collection of (**partition_key**, ), 

When **in memory partition selection** is implemented if **public_partitions** is some Python collection then in memory partition selection is used.

## Note on implementation
Since join API is pretty different in different frameworks it makes sense to implement join based PipelineOperation method:

```
class PipelineOperations:
  def filter_partitions(self, col, partitions):
```

[This function in prototype](https://github.com/OpenMined/PipelineDP/blob/04a04d2f31e2299135a4000d2134d71d8f121f7b/prototype/private_beam.py#L181).

**Output**:
a collection of (**partition_key**, **data**)
which contains all elements of **col** which are in **public_partitions**

## Links

1. [Reference doc](https://docs.google.com/document/d/1cvfAU4XwglRgLc7XP9qCf5a6iZRajqVVsH7s5URY-UU/edit#bookmark=id.mp21ow1ze2ps)
2.  [Prototype](https://github.com/OpenMined/PipelineDP/blob/04a04d2f31e2299135a4000d2134d71d8f121f7b/prototype/private_beam.py#L184)

**Comment by lovroprepolec** [comment]
I would be interested in taking this.

**Comment by dvadym** [comment]
Thank you! If you have any questions please ask, I'm happy to help
