### ISSUE TITLE
Using accumulators in LocalOperations

### ISSUE THREAD

**Issue by dvadym** [OpenMined/PipelineDP#42]
# Context

Currently the development of [Accumulator Framework](https://github.com/OpenMined/PipelineDP/issues/37) is in progress. The idea is that **Accumulator Framework** is independent of the pipeline framework. This issue is about implementing usage of **Accumulator Framework** with LocalOperations (local use without any pipeline framework). 

The interface of accumulators:

```
class Accumulator(ABC):
      def merge(cls,  accumulators: Iterable[Accumulator]) -> Accumulator 
      def add_accumulator(self, accumulator:Accumulator) -> Accumulator # returns itself
      def compute_metrics()
```

# Goals
To implement the method of [LocalOperations](https://github.com/OpenMined/PipelineDP/blob/65d00ee6c906a36b8a173ddbb83d7e3bf71905b4/pipeline_dp/pipeline_operations.py#L161):

`def reduce_accumulators_per_key(self, col):`

where **col**  is Iterable which contains elements:  (key, accumulator) 

and the return is a list of elements (key, accumulator), such that all elements per each key are merged.

**Comment by zachferr** [comment]
I'll take this since no one has yet.

**Comment by dvadym** [comment]
Sure, thanks!
