### ISSUE TITLE
Budget accounting

### ISSUE THREAD

**Issue by dvadym** [OpenMined/PipelineDP#5]
## Context 

The privacy budget accounting is an important feature of the DP aggregation system. For now we will work with Basic Composition. In future some advanced composition methods might be used.

Let’s consider the budget as a pair (eps, delta).

Let’s remind that the basic composition is: (𝜺_1, 𝛿_1) + (𝜺_2, 𝛿_2) =  (𝜺_1+𝜺_2,𝛿_1+𝛿_2), i.e. applying of two DP mechanisms lead to the usage of the privacy budget equals to the sum of privacy budgets of both mechanisms.

PipelineDP will allow to have multiple DP operations in one pipeline so it is required to split the privacy budget between those DP operations. Splitting the budget manually is a tedious and error-prone procedure. So PipelineDP should help with that

## Goals

 Implement class **BudgetAccountant** with API:

```
class BudgetAccountant:
 def __init__(self, total_eps : double, total_delta : double):
 def request_budget(self, weight : double, use_eps : bool, use_delta : bool) -> Budget
 def compute_budgets(self):

class Budget:
  @property def eps(self):
  @property def delta(self):

```

The idea is that BudgetAccountant collects all requests on budget usage from different DP operations. And **request_budget()** returns a Budget object which does not have yet eps/delta. And then when the pipeline is constructed, (i.e. all DP operations are known) **compute_budget** is called and it splits (**total_eps**, **total_delta**) over all requests proportionally to their weights. 

**Note**: some differential private operations might not need eps or delta, that is why **use_eps** and **use_delta** parameters are used.

**Note**: for some DP operations it might be more important to get more accurate result, that is why **weight** parameter is used.

## Links

[Prototype](https://github.com/OpenMined/PipelineDP/blob/04a04d2f31e2299135a4000d2134d71d8f121f7b/prototype/budget_accounting.py)

**Note:** Please consider the prototype with a grain of salt, it's not a production code, it's mostly as an example.

**Comment by AlexandraImbrisca** [comment]
Hi! I would like to work on this. Anyone is free to join if they are interested 👋🏻

**Comment by dvadym** [comment]
Sure, thank you! If you have any questions, please ask. I'm happy to help

**Comment by dvadym** [comment]
Thanks AlexandraImbrisca for implementing this!
