### ISSUE TITLE
Create Python wrappers for private partitions selection

### ISSUE THREAD

**Issue by dvadym** [OpenMined/PipelineDP#52]
## Context

**Definition**:  The partition keys are called private if they are not known in advance but are determined based on the data contributed by the individuals in the datasets. [More details](https://docs.google.com/document/d/1cvfAU4XwglRgLc7XP9qCf5a6iZRajqVVsH7s5URY-UU/edit#bookmark=id.q22n9ntoismv).

**The private partition selection** is a procedure that ensures that the output partitions keys are selected in DP fashion. There are at least 2 methods for private partition selection. [More details](https://docs.google.com/document/d/1cvfAU4XwglRgLc7XP9qCf5a6iZRajqVVsH7s5URY-UU/edit#bookmark=id.bhpn0i81xkc):
1. Truncated geometric thresholding ([paper](https://arxiv.org/pdf/2006.03684))
2. Laplace/Gaussian thresholding ([paper](https://github.com/google/differential-privacy/blob/main/common_docs/Delta_For_Thresholding.pdf)).

[PyDP](https://github.com/OpenMined/PyDP/tree/dev/src/bindings/PyDP/algorithms) project provides wrappers for [Google C++ DP library](https://github.com/google/differential-privacy/tree/main/cc/algorithms). But wrappers for private partition selection are missing.

## Goals
To implement wrappers for **Truncated geometric thresholding** and **Laplace/Gaussian thresholding** in [PyDP](https://github.com/OpenMined/PyDP/tree/dev/src/bindings/PyDP/algorithms).

C++ library API: 
1. [Truncated geometric thresholding](https://github.com/google/differential-privacy/blob/8e50da312ba9ab8e001aed0a3cdb43e604fb132e/cc/algorithms/partition-selection.h#L193) (it's there called PreaggPartitionSelection, which is an old name, it's better to use a new in wrappers)
2. [LaplacePartitionSelection](https://github.com/google/differential-privacy/blob/8e50da312ba9ab8e001aed0a3cdb43e604fb132e/cc/algorithms/partition-selection.h#L278).
3. [GaussianPartitionSelection](https://github.com/google/differential-privacy/blob/8e50da312ba9ab8e001aed0a3cdb43e604fb132e/cc/algorithms/partition-selection.h#L411).

### Python API
1. Pybind wrapper for [PartitionSelectionStrategy](https://github.com/google/differential-privacy/blob/8e50da312ba9ab8e001aed0a3cdb43e604fb132e/cc/algorithms/partition-selection.h#L43), with 1 method [ShouldKeep](https://github.com/google/differential-privacy/blob/8e50da312ba9ab8e001aed0a3cdb43e604fb132e/cc/algorithms/partition-selection.h#L108).
2. Functions:

```
def create_truncted_geometric_partition_strategy(<all needed params>) -> PartitionSelectionStrategy
def create_laplace_partition_strategy(<all needed params>) -> PartitionSelectionStrategy
def create_gaussian_partition_strategy(<all needed params>) -> PartitionSelectionStrategy
```

**Comment by levzlotnik** [comment]
Hey, I'd like to take over this issue.

**Comment by dvadym** [comment]
Sure, thanks!

**Comment by levzlotnik** [comment]
Hey, the PR on PyDP#374 was merged. 
The newly added API and pseudo-code of usage:
```python
from pydp.algorithms.partition_selection import create_paritition_strategy
k_tsgd_selector = create_partition_strategy("truncated_geometric", 
                      epsilon, delta, max_partitions) # type: PartitionSelectionStrategy
...
def get_dp_partitions(database, partition_selector: PartitionSelectionStrategy):
    database_partitions = database.partition_by(KEY)
    for partition in database_partitions:
        if partition_selector.should_keep(paritition.num_users):
            yield partition

dp_partitions = get_dp_partitions(data, k_tsgd_selector)
```

**Comment by dvadym** [comment]
Thanks!
