### ISSUE TITLE
DP Count Accumulator

### ISSUE THREAD

**Issue by dvadym** [OpenMined/PipelineDP#53]
## Goals

To implement class `CountAccumulator` which computes a Differential Private count of elements. 
`CountAccumulator` should be a sub-class of [Accumulator](https://github.com/OpenMined/PipelineDP/blob/5f8e2b5e1265af6e29f3c2fb79d0c9846a63ba43/pipeline_dp/accumulator.py#L12) class.

## API

```
@dataclass
class CountParams:
   noise:NoiseKind

class CountAccumulator(Accumulator): 
    def __init__(params:CountParams, values)
    def add_value(self, value)  # returns self
    def add_accumulator(self, accumulator: 'CountAccumulator')  # returns self
    def compute_metrics(self) -> double   
```

## Stages of the development

1. Implement count computation.
2. Add anonymization to output, by using function from [dp_computations](https://github.com/OpenMined/PipelineDP/blob/main/pipeline_dp/dp_computations.py) (this is better to do in a separate PR) (more details next section)

## Adding anonymization
The idea is to use function [dp_count](https://github.com/OpenMined/PipelineDP/blob/864675a98c507c4965104ade621d1609d2776d7b/pipeline_dp/dp_computations.py#L180)

For dp_count the following parameters are needed:
```
    eps: float
    delta: float
    max_partitions_contributed: int
    max_contributions_per_partition: int
    noise_kind: pipeline_dp.NoiseKind 
```

So in order to add privacy:
1.Extend `CountParams` with those paramers  (note: now `CountParams` is very similar to `MeanVarParams` in dp_computations, but in future they will likely diverge, so it's better to have a separate structs)
2.Use dp_count

## PrivacyIDCountAccumulator  (new section)
The idea is that all values in the constructor of the accumulator comes from the same **privacy_id** (because the accumulator is created after we do `group_by` by **privacy_id**). So we know that when the accumulator is created, there is one 1 **privacy_id** and only 1 accumulator has values from this **privacy_id**. So we can count the same way as with `CountAccumulator`, just we start with `1` not with l`en(values)`.

**Note**: `add_value` can't be used. So no need to implement (in the cases when `add_value` is needed, this accumulator can't be used, that's fine).

**Comment by lovroprepolec** [comment]
I am interested in this one instead of #43

**Comment by dvadym** [comment]
Sure, thanks!

**Comment by dvadym** [comment]
FYI Adding anonymization section is added in issue description
