### ISSUE TITLE
Spark adapter

### ISSUE THREAD

**Issue by dvadym** [OpenMined/PipelineDP#6]
## Context

**PipelineOperations** interface provides interface with generic  pipeline operations and it allows us to encapsulate a pipeline framework (Apache Beam or Apache Spark or other).

## Goal 

Implement **SparkOperations** class, which is inherited from **PipelineOperations** and implements all abstract methods using Apache Spark API

For example 

```
def map(self, col, fn, stage_name: str):
	return col.map(fn)
```

**Note**: stage_name is needed for Beam, and it might be ignored for **SparkPipelineOperations** 

**Note**: it is required to investigate how well the current PipelineOperation model is consistent with Spark APIs.

**Note**: it is better to split an implementation of different methods in different pull requests.

## Links
TODO: add a link to PipelineOperations sources when [pull request](https://github.com/OpenMined/PipelineDP/pull/2) is submitted

**Comment by boyaryn** [comment]
Hello,
I use Spark in my everyday job and can implement **SparkOperations** class.

**Comment by dvadym** [comment]
Thank you! 

I've assigned this issue to you. If you have any questions please feel free to ask.

**Comment by boyaryn** [comment]
Thanks!

I've created a pull request: https://github.com/OpenMined/PipelineDP/pull/14

Could you review it or assign reviewers when you have free time?
