### ISSUE TITLE
DP Sum Accumulator

### ISSUE THREAD

**Issue by dvadym** [OpenMined/PipelineDP#61]
## Goals

To implement class `SumAccumulator` which computes a Differential Private sum of elements. 
`SumAccumulator` should be a sub-class of [Accumulator](https://github.com/OpenMined/PipelineDP/blob/84bbf45740dcdc197c2c20a75b8eaaf6b1f2ecab/pipeline_dp/accumulator.py#L29) class. There is a class [`CountAccumulator`](https://github.com/OpenMined/PipelineDP/blob/84bbf45740dcdc197c2c20a75b8eaaf6b1f2ecab/pipeline_dp/accumulator.py#L159) (DP part hasn't been yet implemented), which might be used as an example.

## API

```
@dataclass
class SumParams:
   noise:NoiseKind
   noise_std:float

class SumAccumulator(Accumulator): 
    def __init__(params:SumParams, values)
    def add_value(self, value)  # returns self
    def add_accumulator(self, accumulator: 'SumAccumulator')  # returns self
    def compute_metrics(self) -> float   
```

## Stages of the development

1. Implement sum computation.
2. Add anonymization to output, by using function from [dp_computations](https://github.com/OpenMined/PipelineDP/blob/main/pipeline_dp/dp_computations.py) (this is better to do in a separate PR) (more details next section)

## Adding anonymization
The idea is to use function [dp_sum](https://github.com/OpenMined/PipelineDP/blob/84bbf45740dcdc197c2c20a75b8eaaf6b1f2ecab/pipeline_dp/dp_computations.py#L198).

For dp_sum the following parameters are needed:
```
    eps: float
    delta: float
    max_partitions_contributed: int
    max_contributions_per_partition: int
    noise_kind: pipeline_dp.NoiseKind 
```

**Comment by zachferr** [comment]
I'll take this. Thanks!

**Comment by dvadym** [comment]
Thanks!
