### ISSUE TITLE
Unifying API of BudgetAccountant and PLDBudgetAccountant

### ISSUE THREAD

**Issue by dvadym** [OpenMined/PipelineDP#68]
# Context 
The privacy budget accounting is an important feature of the DP aggregation system. Currently there are 2 [BudgetAccoutant](https://github.com/OpenMined/PipelineDP/blob/24f9a7bd6c488e68d8297b031999525a5971e235/pipeline_dp/budget_accounting.py#L56) and [PLDBudgetAccountant](https://github.com/OpenMined/PipelineDP/blob/24f9a7bd6c488e68d8297b031999525a5971e235/pipeline_dp/budget_accounting.py#L143). 

The `BudgetAccountant` uses the naive composition, namely the total budget is the sum of budgets:

(𝜺_1, 𝛿_1) + (𝜺_2, 𝛿_2) = (𝜺_1+𝜺_2,𝛿_1+𝛿_2).

While PLDBudgetAccountant uses Privacy Loss Distribution (PLD) method for advance composition. PLD computations are implemented in [dp_accounting](https://github.com/google/differential-privacy/tree/main/python/dp_accounting) library. 

PLD is more effective from accuracy point of view (i.e. it's possible to add less noise to the result, while ensuring the same privacy guarantees), but have some limitations (eg. it might take long time for PLD computations). In future it's possible that more accounts will be implemented.

## How API of BudgetAccounant and PLDBudgetAccountant differs now
1. Both of them have `request_budget`, which have different arguments and different return types

2. Both of them `compute_budgets` methods, w/o argument and returns. But implementations are different.

The idea is to unify arguments and return of `request_budget` (and to make corresponding changes in the implementation)

# Goals
Introduce the common interface for these 2 classes, to ensure that they might be used in polymorphic way.

# Changes
1.Renaming `BudgetAccounant` -> `NaiveBudgetAccounant`

2.Introducing a base abstract class

```
@abstract
class BudgetAccounant:
   @abstractmethod
   def request_budget(self, noise_kind: NoiseKind, sensitivity: float = 1,weight: float = 1, count: int = 1) ->  MechanismSpec:

   @abstractmethod
   def request_budget():

```

3.Updating `MechanismSpec` by adding properties   

```
@dataclass
class MechanismSpec:
    ... # as now 
   @property
    def eps(self):

   @property
    def delta(self):

```

4.Making corresponding changes in implementation and tests

**Comment by zachferr** [comment]
I can work on this

**Comment by dvadym** [comment]
Thanks!

**Comment by levzlotnik** [comment]
Hey @dvadym and @zachferr, 
As we also now have implementations of vector aggregations - I'd like to request an additional feature from this API.
```python
@abstract
class BudgetAccountant:
    ... # as already noted before me
    # and also:
    @abstractmethod
    def request_equally_split_budgets(self, n_splits, weight=1, ...) -> List[MechanismSpec]:
        """Creates a list of `n_splits` uniformly split budgets, 
        where applying `n_splits` mechanisms with these specs would yield
        an (eps, delta)-DP composition of mechanisms."""
        pass
```
This would make it easier to provide parameters for compositions of mechanisms, and especially so for vector aggregations (where we have to split budget across the feature map).

**Comment by dvadym** [comment]
I agree that being able to request budget for multiple mechanisms is useful feature, I've updated API in this issue description:

def request_budget(self, noise_kind: NoiseKind, sensitivity: float = 1,weight: float = 1, **count: int = 1**) ->  MechanismSpec:

**Note**: count is better than split, because it's up to BudgetAccountant to decide how to "split" budget, in case of advance composition (eg. PLD) it's more complicated than just uniform split (but more effective)
