### ISSUE TITLE
Beam public API

### ISSUE THREAD

**Issue by dvadym** [OpenMined/PipelineDP#69]
# Context

The design doc separates PipelineDP on layers - the public API and DP implementation (3 layers - Pipeline operations, DP library and DPEngine). The public API is the API for general users, which is designed with keeping in mind the following goals: understandable for non-dp experts, easy to use correctly and hard to misuse.
Both DP algorithms implementation and the public API are pretty complicated. So in order not to work on 2 complicated things simultaneously, they were separated in different development stages. This issue is about starting development of the public API.
## Implementation API
The main abstraction of the implementation is [DPEngine](https://github.com/OpenMined/PipelineDP/blob/24f9a7bd6c488e68d8297b031999525a5971e235/pipeline_dp/dp_engine.py#L28), which performs high level management of DP aggregations. 
There is method [DPEngine.aggregate](https://github.com/OpenMined/PipelineDP/blob/24f9a7bd6c488e68d8297b031999525a5971e235/pipeline_dp/dp_engine.py#L40) 
which performs DP aggregations (like COUNT, SUM, MEAN etc)
**Note**: `DPEngine.aggregate` is in development, it’s not yet working, expected to work in ~3 weeks. It doesn’t block development of the public API.

# Main abstractions of the public API
So the main abstractions for Beam Public API:
1. `PrivatePCollection` manages data to be anonymized. The main purpose of `PrivatePCollection` is to make hard incidental privacy errors. `PrivatePCollection` provides guarantees that only anonymized data within the specified privacy budget can be extracted from it.
2. `PrivatePTransforms` which are privacy preserving transformations on `PrivatePCollections`. Each `PrivatePTransform` returns `PrivatePCollection` or  `PCollection` with anonymized data.

**Notes**: 
1. Those abstractions correspond to main Beam abstractions PCollection and PTransform (more in [Beam Programming Guide](https://beam.apache.org/documentation/programming-guide/)).
2. `PrivatePCollection` tracks privacy ids and keeps a state necessary for anonymization. 
3. Only `PrivatePTransforms` can be applied to `PrivatePCollections`.
4. `PrivatePTransforms` might return `PrivatePCollection` or `PCollection` (with anonymized data).

# MVP of the public API.
Let us start with something simple - creating `PrivatePCollection` and performing DP sum. And then we will extend further. 
Let all public API is in **private_beam.py** file.

## Snippet of the public API MVP usage
Let’s use Netflix prize dataset as in [example](https://github.com/OpenMined/PipelineDP/blob/main/examples/movie_view_ratings.py). 

```
import private_beam as pbeam
with beam.Pipeline(runner=runner) as pipeline:
     movie_views = … # read
     budget_accountant = pipeline_dp.BudgetAccountant(epsilon=1, delta=1e-6)  # BudgetAccountant is already implemented
     pcol = col |  "Creates PrivatePCollection" >> 
            pbeam.MakePrivate(budget_accountant,  privacy_id_extractor = lambda mv: mv.user_id)
     sum_params = SumParams(max_partitions_contributed=2, max_contributions_per_partition=1, low=1, high=5)

     sum_ratings_per_movie = pcol | "Computes sum of rating per movie" >> 
                              pbeam.Sum(sum_ratings, partition_id_extractor = lambda mv.movie_id, value_extractor = mv.rating)
     sum_ratings_per_date = pcol | "Computes sum of rating per day" >> 
                              pbeam.Sum(sum_ratings, partition_id_extractor = lambda mv.date, value_extractor = mv.rating)

     budget_accountant.compute_budgets()  # it performs budget split among DP aggregations
```

## List of objects in MVP
So MVP will contain
1. class `PrivatePCollection`
2. classes `MakePrivate` and `Sum`  (PrivatePTransforms)
3. dataclass `SumParams` (with parameters that needed for running DP sum)

## Implementation of the public API 
1. `PrivatePCollection` is a wrapper around `PCollection` which contains user data and it contains all necessary data (eg. BudgetAccountant).
It implementens `__or__` operator (as in [PCollection](https://github.com/apache/beam/blob/7587508e5b64258e66fa9ac10e3610893cf4c91e/sdks/python/apache_beam/pvalue.py#L136 ) ) in order to provide Beam style syntax.
2. Only `PrivatePTransforms` might be applied to `PrivatePCollection`.
3. `PrivatePTransform` is a class which performs operations on the PrivatePCollection underlying data by using [DPEngine.aggregate](https://github.com/OpenMined/PipelineDP/blob/24f9a7bd6c488e68d8297b031999525a5971e235/pipeline_dp/dp_engine.py#L40).

**Comment by preethiraghavan1** [comment]
Hi Vadym, could I work on this?

**Comment by dvadym** [comment]
Sure, thank you!
