### ISSUE TITLE
Local pipeline operations adapter

### ISSUE THREAD

**Issue by dvadym** [OpenMined/PipelineDP#7]
## Context

**PipelineOperations** interface provides interface with generic  pipeline operations and it allows us to encapsulate a pipeline framework (Apache Beam or Apache Spark or other).

 One of the options is to run “locally”, without any pipeline framework. For example it might be convenient to perform DP aggregations on Pandas DataFrames (it's outside of scope of this issue).

## Goal

 Implement **LocalOperations** class, which is inherited from **PipelineOperations** and implements all abstract methods using pure Python.

Eg. 

```
def map(self, col, fn, stage_name: str):
	return map(col, fn)
```

where col is iterable.

**Note**: stage_name is needed only for Beam, and it might be ignored for **LocalPipelineOperations**. 

**Note**: because of nuances of how DP pipelines work, all operations should be lazy, luckily Python has a concept of [generators](https://wiki.python.org/moin/Generators), which should simplify lazy implementation. 

**Note**: it is better to split an implementation of different methods in different pull requests.

## Links
TODO: add a link to PipelineOperations sources when [pull request](https://github.com/OpenMined/PipelineDP/pull/2) is submitted

**Comment by replomancer** [comment]
I'd like to do that. If someone else is interested, we can divide work by methods.

**Comment by zachferr** [comment]
I'd also like to work on this.

**Comment by dvadym** [comment]
> I'd also like to work on this.

Sure, thank you! Please sync with replomancer on how to divide methods to implement

**Comment by dvadym** [comment]
FYI

SamplePerKey has been implemented in https://github.com/OpenMined/PipelineDP/pull/32 (as part of the implementation of Contribution bounding)

**Comment by dvadym** [comment]
FYI: I've added another LocalOperations related [issue](https://github.com/OpenMined/PipelineDP/issues/42) - using accumulators in LocalOperations. If you'd like to work on that issue, please write on it.
