### ISSUE TITLE
Spark public API

### ISSUE THREAD

**Issue by dvadym** [OpenMined/PipelineDP#70]
# Context

The design doc separates PipelineDP on layers - the public API and DP implementation (3 layers - Pipeline operations, DP library and DPEngine). The public API is the API for general users, which is designed with keeping in mind the following goals: understandable for non-dp experts, easy to use correctly and hard to misuse.
Both DP algorithms implementation and the public API are pretty complicated. So in order not to work on 2 complicated things simultaneously, they were separated in different development stages. This issue is about starting development of the public API.
## Implementation API
The main abstraction of the implementation is [DPEngine](https://github.com/OpenMined/PipelineDP/blob/24f9a7bd6c488e68d8297b031999525a5971e235/pipeline_dp/dp_engine.py#L28), which performs high level management of DP aggregations. 
There is method [DPEngine.aggregate](https://github.com/OpenMined/PipelineDP/blob/24f9a7bd6c488e68d8297b031999525a5971e235/pipeline_dp/dp_engine.py#L40) 
which performs DP aggregations (like COUNT, SUM, MEAN etc)
**Note**: `DPEngine.aggregate` is in development, it’s not yet working, expected to work in ~3 weeks. It doesn’t block development of the public API.

# Main abstractions of the public API
**Note:** Those ideas are direct translation from Beam API. In general it's nice to have Beam and Spark APIs are conceptually close, but of course it is desirable to have Spark API to be in Spark Style. I'm not that familiar with Spark, please advice if there is something can be done better.

So the main abstraction of Spark Public API is `PrivateRDD` which manages data to be anonymized. The main purpose of `PrivateRDD` is to make hard incidental privacy errors. The API of `PrivateRDD` provides guarantees that only anonymized data within the specified privacy budget can be extracted from it.

`PrivateRDD` has Private Transformations that return `PrivateRDD` or `RDD` (with anonymized data).

**Notes**: 
1. `PrivateRDD` tracks privacy ids and keeps a state necessary for anonymization. 
2. Private Transformations might return `PrivateRDD` or `RDD` (with anonymized data).

# MVP of the public API.
Let us start with something simple - creating `PrivateRDD` and performing DP sum. And then we will extend further. 
Let all public API is in **private_spark.py** file.

## Snippet of the public API MVP usage
Let’s use Netflix prize dataset as in [example](https://github.com/OpenMined/PipelineDP/blob/main/examples/movie_view_ratings.py). 

```
import private_spark as pspark
movie_views = … # read
budget_accountant = pipeline_dp.BudgetAccountant(epsilon=1, delta=1e-6)  # BudgetAccountant is already implemented
prdd = pspark.makePrivate(movie_views, budget_accountant,  privacy_id_extractor = lambda mv: mv.user_id)
sum_params = SumParams(max_partitions_contributed=2, max_contributions_per_partition=1, low=1, high=5)

sum_ratings_per_movie = prdd.sum(sum_ratings, partition_id_extractor = lambda mv.movie_id, value_extractor = mv.rating)
sum_ratings_per_date = prdd.sum(sum_ratings, partition_id_extractor = lambda mv.date, value_extractor = mv.rating)

budget_accountant.compute_budgets()  # it performs budget split among DP aggregations
```

## List of objects in MVP
So MVP will contain
1. class `PrivateRDD` with transformation sum()
2. function `makePrivate` 
3. dataclass `SumParams` (with parameters that needed for running DP sum)

## Implementation of the public API 
1. `PrivateRDD` is a wrapper around `RDD` which contains user data and it contains all necessary data (eg. BudgetAccountant).
3. Private Transforms performs operations on the `PrivateRDD` underlying data by using [DPEngine.aggregate](https://github.com/OpenMined/PipelineDP/blob/24f9a7bd6c488e68d8297b031999525a5971e235/pipeline_dp/dp_engine.py#L40).

**Comment by boyaryn** [comment]
Hi Vadim, I'd like to work on this.

**Comment by dvadym** [comment]
Sure, thanks!
