### ISSUE TITLE
Extend API of BudgetAccountants

### ISSUE THREAD

**Issue by dvadym** [OpenMined/PipelineDP#78]
# Context

The current API ([code](https://github.com/OpenMined/PipelineDP/blob/40644374e2c5edb69ffc4c832f87b66750399861/pipeline_dp/budget_accounting.py#L13)) of BudgetAccount is

```
class BudgetAccountant(abc.ABC):
    """Base class for budget accountants."""
    def request_budget(self,
                       noise_kind: NoiseKind,
                       sensitivity: float = 1,
                       weight: float = 1) -> MechanismSpec:
    def compute_budgets(self):
```

where 

```
class MechanismSpec:
    @property
    def noise_standard_deviation(self):
    @property
    def eps(self):
    @property
    def delta(self):
```        

# To implement
The idea is to introduce a few additional parameters in request_budget is to implemented [NativeBudgetAccountant](https://github.com/OpenMined/PipelineDP/blob/40644374e2c5edb69ffc4c832f87b66750399861/pipeline_dp/budget_accounting.py#L96) and in [PLDBudgetAccountant](https://github.com/OpenMined/PipelineDP/blob/40644374e2c5edb69ffc4c832f87b66750399861/pipeline_dp/budget_accounting.py#L170):

1. `count` which says how many this mechanism is going to be applied
2. `noise_standard_deviation` to allow users to fix which is std for the current mechanism. Note, that in case if such std can't be achieved not exceeding total budget then compute_budget should fail with the corresponding exception.

# Steps of implementation
1. Introduce API
2. Implement in `NativeBudgetAccountant`
3.  Implement in `PLDBudgetAccountant`

**Note:** Steps 2 and 3 are independent.

**Comment by zachferr** [comment]
I can do steps 1&2

**Comment by dvadym** [comment]
Thanks!
