### ISSUE TITLE
Accumulator for computing Mean and Variance

### ISSUE THREAD

**Issue by dvadym** [OpenMined/PipelineDP#9]
## Context

The [Accumulator Framework](https://github.com/OpenMined/PipelineDP/issues/37) has been developed for flexible computing DP metrics (based on when the API user requested).

The accumulator is the object that accumulates values and produces the aggregated result. The computing of all Differential Private (DP) metrics is done in corresponding accumulators.

Computing of COUNT, SUM, MEAN, VARIANCE might be achieved in one accumulator using summation, [more details](https://docs.google.com/document/d/12fGPsf678R2AGb9x1xicRhfMTj4IbZK8zddApK667uE/edit?resourcekey=0-Leq3Y6bPlYzDUBfEZcYIgA#bookmark=id.aw7wfzc3ylo9).
 
## Goals

Implement class **MeanVarAccumulator** which computes any subset of **COUNT**, **SUM**, **MEAN**, **VARIANCE** metrics.

**Note**: please advise on a better name for the class.

## API

```
class Metrics(Enum): # it already exists
    COUNT = 'count',
    SUM = 'sum',
    MEAN = 'mean',
    VAR = 'variance'

class MeanVarAccumulator(Accumulator):
    def __init__(MeanVarParams, values: Iterable[double])
    def merge(cls,  aggregators: Iterable[MeanVarAccumulator]) -> MeanVarAccumulator
    def compute_metrics() -> tuple
```

## Stages of the development

1. Implement not DP aggregations.
2. Add anonymization with DP, using [functions](https://github.com/OpenMined/PipelineDP/blob/main/pipeline_dp/dp_computations.py).

**Comment by say-yam** [comment]
Would like to work on it; i do think that it could be divided among folks.

**Comment by dvadym** [comment]
Sure, thank you! If you have any questions, please ask. I'm happy to help

**Comment by dvadym** [comment]
Clarification about SumAggregator class:

## Usage
The idea is to use SumAggregator in a pipeline flow like this:

Let a collection **col1** have elements ((pid, pk), [v]) (pid = privacy id, pk = partition key, v = value)

1. `aggregated_pid_pk = pipeline_operations.map_values(col1, lambda list_values: SumAggregator(list_values)) `
 So **aggregated_pid_pk** has elements ((pid, pk), SumAggregator), where SumAggregator has aggregated values per (pid, pk).

2. Some processing for bounding cross-partition contributions

3. We have collection: **col2** with elements (pk, SumAggregator)
`  aggregated_pk = pipeline_operations.combine_values()  # and here merging of SumAggregators is needed`
 So **aggregated_pk** has elements (pk, SumAggregator), where SumAggregator has aggregated values per (pk).

## Dependencies

**SumAggregator** should know nothing about PipelineOperations. It's better from design perspective - splitting on layers and easier to test.

## Notes on implementation
In design doc it's written in terms of vector summation. Instead of vectors it's better to have some fields, i.e. SumAggregator can have

```
class SumAggregator:
  # some other functions/variables

  privacy_id_count: int
  count: int
  sum: double
  sum_squares: double
```

**Comment by replomancer** [comment]
I'd like to do it.
